config/routes.rb
Rails.application.routes.draw do
  namespace :cp do
    resources :brands
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cp.rb
module Cp
  def self.table_name_prefix
    "cp_"
  end
end

app/models/cp/brand.rb
class Cp::Brand < ApplicationRecord
  serialize :categories, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cp/brands_controller.rb
class Cp::BrandsController < ApplicationController
  before_action :set_cp_brand, only: %i[ show edit update destroy ]

  # GET /cp/brands or /cp/brands.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: CpBrandsDatatable.new(params) }
    end
  end

  # GET /cp/brands/1 or /cp/brands/1.json
  def show
  end

  # GET /cp/brands/new
  def new
    @cp_brand = Cp::Brand.new
  end

  # GET /cp/brands/1/edit
  def edit
  end

  # POST /cp/brands or /cp/brands.json
  def create
    @cp_brand = Cp::Brand.new(cp_brand_params)

    respond_to do |format|
      if @cp_brand.save
        format.html { redirect_to cp_brand_url(@cp_brand), notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @cp_brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cp_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cp/brands/1 or /cp/brands/1.json
  def update
    respond_to do |format|
      if @cp_brand.update(cp_brand_params)
        format.html { redirect_to cp_brand_url(@cp_brand), notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @cp_brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cp_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cp/brands/1 or /cp/brands/1.json
  def destroy
    @cp_brand.destroy

    respond_to do |format|
      format.html { redirect_to cp_brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cp_brand
      @cp_brand = Cp::Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cp_brand_params
      params.fetch(:cp_brand, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cp/brands_helper.rb
module Cp::BrandsHelper
end

app/views/cp/brands/_brand.html.erb
<div id="<%= dom_id brand %>">
</div>

app/views/cp/brands/_form.html.erb
<%= form_with(model: cp_brand) do |form| %>
  <% if cp_brand.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cp_brand.errors.count, "error") %> prohibited this cp_brand from being saved:</h2>

      <ul>
        <% cp_brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cp/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render "form", cp_brand: @cp_brand %>

<br>

<div>
  <%= link_to "Show this brand", @cp_brand %> |
  <%= link_to "Back to brands", cp_brands_path %>
</div>

app/views/cp/brands/index.html.erb
<div class="page-header d-print-none">
  <div class="container-xl">
    <div class="row g-2 align-items-center">
      <div class="col">
        <h2 class="page-title" data-controller="hello" id="title">
          Brands
        </h2>
      </div>
    </div>
  </div>
</div>

<div class="page-body">
  <div class="container-xl">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table" data-controller="brands" id="brands-datatable" data-brands-target="table" data-source="<%= cp_brands_path(format: :json) %>">
              <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Address</th>
                <th>Website</th>
                <th>Categories</th>
              </tr>
              </thead>
              <tbody class="table-tbody">
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/cp/brands/new.html.erb
<h1>New brand</h1>

<%= render "form", cp_brand: @cp_brand %>

<br>

<div>
  <%= link_to "Back to brands", cp_brands_path %>
</div>

app/views/cp/brands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cp_brand %>

<div>
  <%= link_to "Edit this brand", edit_cp_brand_path(@cp_brand) %> |
  <%= link_to "Back to brands", cp_brands_path %>

  <%= button_to "Destroy this brand", @cp_brand, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CpDatatable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>